add_test( ArrayIntTest.InitTest /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test/ArrayTests [==[--gtest_filter=ArrayIntTest.InitTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayIntTest.InitTest PROPERTIES WORKING_DIRECTORY /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayIntTest.InitZeroTest /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test/ArrayTests [==[--gtest_filter=ArrayIntTest.InitZeroTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayIntTest.InitZeroTest PROPERTIES WORKING_DIRECTORY /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayIntTest.DotProduct /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test/ArrayTests [==[--gtest_filter=ArrayIntTest.DotProduct]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayIntTest.DotProduct PROPERTIES WORKING_DIRECTORY /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayIntTest.AddArray /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test/ArrayTests [==[--gtest_filter=ArrayIntTest.AddArray]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayIntTest.AddArray PROPERTIES WORKING_DIRECTORY /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayIntTest.AddInt /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test/ArrayTests [==[--gtest_filter=ArrayIntTest.AddInt]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayIntTest.AddInt PROPERTIES WORKING_DIRECTORY /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayIntTest.MultInt /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test/ArrayTests [==[--gtest_filter=ArrayIntTest.MultInt]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayIntTest.MultInt PROPERTIES WORKING_DIRECTORY /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayIntTest.SubtractInt /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test/ArrayTests [==[--gtest_filter=ArrayIntTest.SubtractInt]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayIntTest.SubtractInt PROPERTIES WORKING_DIRECTORY /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayFloatTest.InitTest /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test/ArrayTests [==[--gtest_filter=ArrayFloatTest.InitTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayFloatTest.InitTest PROPERTIES WORKING_DIRECTORY /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayFloatTest.DotProduct /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test/ArrayTests [==[--gtest_filter=ArrayFloatTest.DotProduct]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayFloatTest.DotProduct PROPERTIES WORKING_DIRECTORY /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayFloatTest.AddArray /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test/ArrayTests [==[--gtest_filter=ArrayFloatTest.AddArray]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayFloatTest.AddArray PROPERTIES WORKING_DIRECTORY /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayFloatTest.AddFloat /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test/ArrayTests [==[--gtest_filter=ArrayFloatTest.AddFloat]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayFloatTest.AddFloat PROPERTIES WORKING_DIRECTORY /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayFloatTest.MultFloat /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test/ArrayTests [==[--gtest_filter=ArrayFloatTest.MultFloat]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayFloatTest.MultFloat PROPERTIES WORKING_DIRECTORY /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayFloatTest.SubtractFloat /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test/ArrayTests [==[--gtest_filter=ArrayFloatTest.SubtractFloat]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayFloatTest.SubtractFloat PROPERTIES WORKING_DIRECTORY /home/jlb1694/dev/ge-mini/dissertation/sigpro/build_test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( ArrayTests_TESTS ArrayIntTest.InitTest ArrayIntTest.InitZeroTest ArrayIntTest.DotProduct ArrayIntTest.AddArray ArrayIntTest.AddInt ArrayIntTest.MultInt ArrayIntTest.SubtractInt ArrayFloatTest.InitTest ArrayFloatTest.DotProduct ArrayFloatTest.AddArray ArrayFloatTest.AddFloat ArrayFloatTest.MultFloat ArrayFloatTest.SubtractFloat)
